db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
db.username=${POSTGRES_USER}
db.password=${POSTGRES_PASSWORD}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.generate_statistics=false
hibernate.hbm2ddl.auto=validate

server.servlet.mapping=/
server.api.mapping=/api/*

interceptor.path.include=/api/**
interceptor.path.exclude=/api/v1/trainings/training-types
auth.bypass.post.paths=/api/v1/trainees,/api/v1/trainers

swagger.ui.path=/swagger-ui/**
swagger.ui.resource.path=classpath:/META-INF/resources/webjars/swagger-ui/5.32.8/
swagger.api.docs.url=/openapi.json
swagger.api.docs.resource.path=classpath:/META-INF/resources/
swagger.html.url=/swagger-ui.html
swagger.redirect.url=/swagger-ui/index.html?url=/openapi.json