spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

interceptor.path.include=/api/**
interceptor.path.exclude=/api/v1/trainings/training-types
auth.bypass.post.paths=/api/v1/trainees,/api/v1/trainers

info.app.name=Gym CRM System
info.app.description=Spring Boot Implementation of Gym CRM
info.app.version=1.0.0

management.server.port=8081