db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
#db.username=${POSTGRES_USER}
db.username=postgres
#db.password=${POSTGRES_PASSWORD}
db.password=password1234

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=validate