spring:
  application:
    name: trainer-workload-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      group-id: workload-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.example.workload.controller.dto.request.TrainerWorkloadRequest
        max.poll.records: 50
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${SERVER_PORT}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}
  roles-claim: roles

kafka:
  topics:
    trainer-workload-update: "trainer-workload-update-event"
  consumer:
    retry:
      backoff-interval-ms: 1000
      max-attempts: 3

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true


management:
  server:
    port: ${MANAGEMENT_PORT}
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
        readiness:
          include:
            - readinessState
info:
  app:
    name: Trainer Workload Service
    description: Spring Boot Microservice for Trainer Workload Tracking
    version: 1.0.0