server.port=8082

logging.level.root=WARN
logging.level.com.epam.gymcrm.workload=INFO
logging.level.org.springframework.web=WARN

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=never

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false