server.port=8082

logging.level.root=INFO
logging.level.com.epam.gymcrm.workload=INFO
logging.level.org.springframework.web=INFO

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always