spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION}

security.cors.allowed-origins=*
security.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE
security.cors.allowed-headers=Authorization,Content-Type,Cache-Control
security.cors.exposed-headers=Authorization

security.admin.usernames=${ADMIN_USERNAMES:}

services.workload-url=${WORKLOAD_URL}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

resilience4j.circuitbreaker.instances.trainerWorkloadService.sliding-window-size=10
resilience4j.circuitbreaker.instances.trainerWorkloadService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.trainerWorkloadService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.trainerWorkloadService.permitted-number-of-calls-in-half-open-state=3

info.app.name=Gym CRM System
info.app.description=Spring Boot Implementation of Gym CRM
info.app.version=1.0.0

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

management.server.port=8081

management.health.circuitbreakers.enabled=true

management.endpoint.health.probes.enabled=true
management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState,db,dbPrivileges
management.health.db-privileges.required-tables=users,trainees,trainers,trainings,training_types
management.health.db-privileges.required-privileges-by-table.trainee=SELECT,INSERT,UPDATE,DELETE