spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: warn
    org.example.crm: info
    org.springframework.web: warn
    org.hibernate.sql: error

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false